### ISSUE TITLE
WRONG MOD, DISREGARD

### ISSUE THREAD

**Issue by Stick404** [FallingColors/Hexal#125]
I used power distillation on an 8 by 8 matrix grid of 0s and the number 2. Mod pack I was using was the HexxyTest pack on the discord.
Error log and images below.

https://stick404.mindlesstoys.com/quickfileshare/2024-02-22_20.53.15.png

---- Minecraft Crash Report ----
// You're mean.

Time: 2024-02-22 20:45:51
Description: Exception in server tick loop

java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract at.petrak.hexcasting.api.casting.eval.OperationResult operate(at.petrak.hexcasting.api.casting.eval.CastingEnvironment, at.petrak.hexcasting.api.casting.eval.vm.CastingImage, at.petrak.hexcasting.api.casting.eval.vm.SpellContinuation)' of abstract class at.petrak.hexcasting.api.casting.arithmetic.operator.Operator.
	at at.petrak.hexcasting.api.casting.arithmetic.engine.ArithmeticEngine.run(ArithmeticEngine.java:97)
	at at.petrak.hexcasting.api.casting.castables.OperationAction.operate(OperationAction.kt:19)
	at at.petrak.hexcasting.api.casting.iota.PatternIota.execute(PatternIota.java:103)
	at at.petrak.hexcasting.api.casting.eval.vm.CastingVM.executeInner(CastingVM.kt:109)
	at at.petrak.hexcasting.api.casting.eval.vm.FrameEvaluate.evaluate(FrameEvaluate.kt:39)
	at at.petrak.hexcasting.api.casting.eval.vm.CastingVM.queueExecuteAndWrapIotas(CastingVM.kt:53)
	at at.petrak.hexcasting.api.casting.eval.vm.CastingVM.handler$ech000$hexal$executeIotaMacro(CastingVM.kt:596)
	at at.petrak.hexcasting.api.casting.eval.vm.CastingVM.queueExecuteAndWrapIota(CastingVM.kt)
	at at.petrak.hexcasting.api.casting.eval.env.StaffCastEnv.handleNewPatternOnServer(StaffCastEnv.java:105)
	at at.petrak.hexcasting.common.msgs.MsgNewSpellPatternC2S.lambda$handle$0(MsgNewSpellPatternC2S.java:56)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.5.0-21-generic
	Java Version: 17.0.9, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 709551664 bytes (676 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 7700X 8-Core Processor
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Navi 24 [Radeon RX 6400/6500 XT/6500M]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 4352.00
	Graphics card #0 deviceId: 0x743f
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: Raphael
	Graphics card #1 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #1 VRAM (MB): 258.00
	Graphics card #1 deviceId: 0x164e
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 17658.52
	Virtual memory used (MB): 11243.59
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		ae2: Applied Energistics 2 15.0.20
			team_reborn_energy: Energy 3.0.0
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.1.12
		armourers_workshop: Armourer's Workshop 2.0.11
		botania: Botania 1.20.1-443-FABRIC
			fiber: fiber 0.23.0-2
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		carryon: Carry On 2.1.2.7
		chesttracker: Chest Tracker 1.1.23
			libgui: LibGui 8.0.0+1.20
				jankson: Jankson 5.0.1+j1.2.2
				libninepatch: LibNinePatch 1.2.0
			whereisit: Where Is It 1.14.17
		chunkloaders: Chunk Loaders 1.2.8+a
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		collective: Collective 7.30
		computer_cartographer: Computer Cartographer 1.0
		computercraft: CC: Tweaked 1.109.5
			cc_tweaked_cobalt: cobalt 0.9.0
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
			com_jcraft_jzlib: jzlib 1.1.3
			io_netty_netty-codec-http: netty-codec-http 4.1.82.Final
			io_netty_netty-codec-socks: netty-codec-socks 4.1.82.Final
			io_netty_netty-handler-proxy: netty-handler-proxy 4.1.82.Final
		controlling: Controlling For Fabric 12.0.2
		cosmetic-armor: Cosmetic Armor 1.6.0
		crafttweaker: CraftTweaker 14.0.32
			org_javassist_javassist: javassist 3.29.0-GA
			org_reflections_reflections: reflections 0.10.2
		create: Create 0.5.1-d-build.1161+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.9-1
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
				porting_lib_common: Porting Lib Common 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		cupboard: cupboard 1.20.1-2.3
		distanthorizons: Distant Horizons 2.0.1-a
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
		do_a_barrel_roll: Do a Barrel Roll 3.3.7+1.20
			cicada: CICADA 0.5.0+1.20.1-minus
			mixinsquared: MixinSquared 0.1.1
		ducky-periphs: Ducky Peripherals 1.20.1-1.3.1
			org_jblas_jblas: jblas 1.2.5
			org_joml_joml: joml 1.10.5
		dummmmmmy: MmmMmmMmmMmm 1.20-1.8.14
		easyshulkerboxes: Easy Shulker Boxes 8.0.1
			puzzlesapi: Puzzles Api 8.1.4
		elytra-trims: Elytra Trims 2.0.0-beta.4
		emi: EMI 1.1.0+1.20.1+fabric
		emi_enchanting: EMI Enchanting 0.1.0+1.20.1
		emi_loot: EMI Loot 0.6.5+1.20.1
		emitrades: EMI Trades 1.2.1+mc1.20.1
			org_quiltmc_parsers_json: json 0.2.1
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		estrogen: Create: Estrogen 4.0.5-fabric
			jukeboxfix: Jukeboxfix 1.0.0+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabrication: Fabrication 3.4.10+1.20
			lib39-deferral: Lib39 (Deferral) 1.5.0-pre2.2+1.19.3
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		faux-custom-entity-data: Faux-Custom-Entity-Data 6.0.1
		ferritecore: FerriteCore 6.0.1
		figura: Figura 0.1.3-pre.4+1.20.1
			com_github_figuramc_luaj_luaj-core: luaj-core 3.0.7-figura
			com_github_figuramc_luaj_luaj-jse: luaj-jse 3.0.7-figura
			org_java-websocket_java-websocket: Java-WebSocket 1.5.4
		forgeconfigapiport: Forge Config API Port 8.0.0
		geckolib: GeckoLib 4 4.3.1
			com_eliotlash_mclib_mclib: mclib 20
		hexal: Hexal 0.3.0-2
			serialization_hooks: Serialization Hooks 0.4.99999
		hexcasting: Hex Casting 0.11.1-7-pre-619
		hextweaks: Hex Tweaks 1.0.0
		hexxy-dimensions: Hexxy Dimensions 1.2.1
		inventoryprofilesnext: Inventory Profiles Next 1.10.9
		jade: Jade 11.7.0
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.27
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		libipn: libIPN 4.0.1
		libjf: LibJF 3.12.5
			libjf-base: LibJF Base 3.12.5
			libjf-config-commands-v1: LibJF Config Commands 3.12.5
			libjf-config-core-v1: LibJF Config 3.12.5
			libjf-config-reflect-v1: LibJF Config Reflect 3.12.5
			libjf-config-ui-tiny-v1: LibJF Config UI: Tiny 3.12.5
			libjf-data-manipulation-v0: LibJF Data Manipulation 3.12.5
			libjf-data-v0: LibJF Data 3.12.5
			libjf-translate-v1: LibJF Translate 3.12.5
			libjf-unsafe-v0: LibJF Unsafe 3.12.5
			libjf-web-v0: LibJF Web 3.12.5
		lootr: Lootr 0.7.29.75
		maxhealthfix: MaxHealthFix 12.0.2
		mca: Minecraft Comes Alive 7.5.11+1.20.1
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		mixintrace: MixinTrace 1.1.1+1.17
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.9.3
		moreiotas: MoreIotas 0.1.0-4
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		notenoughcrashes: Not Enough Crashes 4.4.7+1.20.1
		observable: Observable 4.4.0
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		packages: Packages 3.4.5+blanket.2
		packetfixer: Packet Fixer 1.2.1
		paginatedadvancements: Paginated Advancements 2.3.0
		patchouli: Patchouli 1.20.1-84-FABRIC
		paucal: PAUCAL 0.6.0-pre-118
		pehkui: Pehkui 3.7.12+1.14.4-1.20.4
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		phonos: Phonos 1.0.0-beta.11+1.20.1
			jsonem: JsonEM 0.2.1+1.20
		plethora: Plethora 1.9.4
			cloth-utils-v1: Cloth Utils v1 4.0.65
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
			sc-library: SwitchCraft Library 1.3.0
		polymorph: Polymorph 0.49.1+1.20.1
		puzzleslib: Puzzles Lib 8.1.15
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		railways: Create: Steam 'n' Rails 1.5.1+fabric-mc1.20.1
		resourcefullib: Resourceful Lib 2.1.20
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		revelationary: Revelationary 1.3.6+1.20.1
		sc-peripherals: SwitchCraft Peripherals 1.7.2
			io_prometheus_simpleclient: simpleclient 0.16.0
			io_prometheus_simpleclient_hotspot: simpleclient_hotspot 0.16.0
			io_prometheus_simpleclient_httpserver: simpleclient_httpserver 0.16.0
			org_cache2k_cache2k-api: cache2k-api 2.6.1.Final
			org_cache2k_cache2k-core: cache2k-core 2.6.1.Final
		searchables: Searchables 1.0.2
		servercore: ServerCore 1.3.9+1.20.1
			placeholder-api: Placeholder API 2.1.2+1.20.1
		simple_cobblestone_generator: Simple cobblestone generator 1.1.15
		spark: spark 1.10.53
		spectrum: Spectrum 1.7.7
			additionalentityattributes: Additional Entity Attributes 1.4.0+1.20.0
			arrowhead: Arrowhead 1.2.0-1.19.4
			fractal: Fractal 1.1.0
			matchbooks: Matchbooks 0.1.0
			org_jgrapht_jgrapht-core: jgrapht-core 1.5.1
			org_jheaps_jheaps: jheaps 0.13
			reverb: Reverb 1.0.0
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		supplementaries: Supplementaries 1.20-2.7.30
		toms_peripherals: Tom's Peripherals 1.2.0
		tooltipfix: ToolTip Fix 1.1.1-1.20
		trinkets: Trinkets 3.7.1
		ultracraft: Ultracraft 1.20.1-2.0.4
			azurelib: AzureLib 2.0.6
			goop: Goop Technology 1.20.1-0.2
			mm: Manningham Mills 2.3
			player-animator: Player Animator 1.0.2-rc1+1.20
		ultracraft-crash-fix: Ultracraft-crash-fix 1.0.0
		veinmining: Vein Mining 1.3.0+1.20.1
			spectrelib: SpectreLib 0.13.15+1.20.1
		vivecraft: Vivecraft 1.20.1-1.1.5
			org_lwjgl_lwjgl-openvr: lwjgl-openvr 3.3.1
			org_lwjgl_lwjgl-openvr_natives-linux: lwjgl-openvr 3.3.1
			org_lwjgl_lwjgl-openvr_natives-macos: lwjgl-openvr 3.3.1
			org_lwjgl_lwjgl-openvr_natives-windows: lwjgl-openvr 3.3.1
		voicechat: Simple Voice Chat 1.20.1-2.5.1
		wearthat: WearThat 1.19.4_1.0.0
		xaerominimap: Xaero's Minimap 23.9.3
		xaeros-map-chest-tracker-integration: Xaero's Map Chest Tracker Integration 1.0.2
			conditional-mixin: conditional mixin 0.4.0
		xaeroworldmap: Xaero's World Map 1.37.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
		yigd: You're in Grave Danger 2.0.0-beta.7
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 1 / 8; [class_3222['Stick_King1'/86, l='ServerLevel[Test]', x=-249.79, y=64.00, z=-307.32]]
	Data Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, Supplementaries Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.20.1
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 1
	Suspected Mods: Minecraft (minecraft), Hexal (hexal), Hex Casting (hexcasting)

**Comment by vgskye** [comment]
you forgot to close the issue
